### PR TITLE
check mkdir returned err

### LINKED ISSUE #16: bug create does not check for existance of issues directory before firing editor
Presence of an issue directory set via PMIT is not checked upfront, but only after writing a bug description.
Would be helpful to know before spending time in writing the description

### PR DESCRIPTION
**Pull request by grantbow**
closes #16
This works great. I think a better implementation is to make
Directory.go:GetRootDir() return empty if the issues directory is missing in
BOTH the non PMIT and PMIT cases. However several tests depend on the bad
behavior and it would require some more refactoring of code and tests which can
be done separately.

### CODE REVIEW

File: bugapp/Create.go [hunk 1]
```diff
@@ -61,7 +61,11 @@ func Create(Args ArgumentList) {
 
 	var mode os.FileMode
 	mode = 0775
-	os.Mkdir(string(dir), mode)
+	err := os.Mkdir(string(dir), mode)
+	if err != nil {
```
Comment (driusan) [inline bugapp/Create.go]: This would be a little cleaner as `if err := os.Mkdir(string(dir), mode); err != nil {`
